### ISSUE TITLE
No beakable page contents

### ISSUE THREAD

**Issue by xiaoleeza** [Esgrove/LaTexCV#1]
Your CV template is so awesome. But when I filling my contents in this template, I find the heading and main contents is break in two pages.

**Comment by Esgrove** [comment]
Yes. It is intended to be only one page, so if the contents don't fit on one page then the body will flip to the next page leaving the header alone. You can either split the contents to multiple pages manually, or  you just have to reduce the contents and/or make the header smaller to fit everything on one page like I did.

**Comment by xiaoleeza** [comment]
Thank you so much, I have splitted the contents to multiple pages manually. this is not complex.
